# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0007_remove_tag_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True, null=True)),
                ('edu_category', models.ManyToManyField(to='category.EduCategory')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.PostCategory')),
                ('tag', models.ManyToManyField(blank=True, to='category.Tag')),
            ],
        ),
    ]
