# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_tag_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post_category',
        ),
    ]
