# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_warning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
