# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_warning', '0004_auto_20171017_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
