# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20171014_0714'),
        ('edu_warning', '0004_historywarning_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historywarning',
            name='edu_category',
        ),
        migrations.AddField(
            model_name='historywarning',
            name='edu_category',
            field=models.ManyToManyField(to='category.EduCategory'),
        ),
        migrations.RemoveField(
            model_name='historywarning',
            name='post_category',
        ),
        migrations.AddField(
            model_name='historywarning',
            name='post_category',
            field=models.ManyToManyField(to='category.PostCategory'),
        ),
    ]
