# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfiles', '0001_initial'),
        ('edu_warning', '0005_questionnaire_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historywarning',
            name='attachment',
        ),
        migrations.AddField(
            model_name='historywarning',
            name='attachment',
            field=models.ManyToManyField(to='uploadfiles.UploadFile'),
        ),
    ]
