# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_warning', '0007_historywarning_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historywarning',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='category.Tag'),
        ),
    ]
