# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_warning', '0008_auto_20171014_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historywarning',
            name='tag',
            field=models.ManyToManyField(to='category.Tag'),
        ),
    ]
