# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_warning', '0007_remove_historywarning_attachment'),
        ('uploadfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_warning.HistoryWarning'),
        ),
    ]
