# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfiles', '0002_auto_20171022_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='project',
            new_name='festival',
        ),
    ]
