# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfiles', '0003_auto_20171022_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
