# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadfiles', '0005_uploadfile_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='Posts',
            new_name='posts',
        ),
    ]
